# Generated by Django 3.0.5 on 2020-06-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyfemiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='Name',
        ),
    ]
