# Generated by Django 3.0.5 on 2020-06-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyfemiapp', '0003_auto_20200603_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
