# Generated by Django 3.0.5 on 2020-06-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyfemiapp', '0004_auto_20200603_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-Date',)},
        ),
    ]
